app/auth.py
import functools
import os

from flask import Blueprint, Flask
from flask import current_app as app
from flask import (flash, g, redirect, render_template, request, session,
                   url_for)
from passlib.hash import sha256_crypt
from werkzeug.exceptions import abort
from werkzeug.security import check_password_hash, generate_password_hash

from app.db import get_db

# A Blueprint is a way to organize a group of related views 
# and other code. Rather than registering views and other 
# code directly with an application, they are registered 
# with a blueprint. Then the blueprint is registered with 
# the application when it is available in the factory function.
bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.before_request
def csrf_protect():
    if request.method == "POST":
        token = str(session.pop('_csrf_token', None))

        form_token = request.form.get('_csrf_token')

        if not token or token != form_token:
            abort(404)

# bp.before_app_request() registers a function that runs 
# before the view function, no matter what URL is requested. 
# load_logged_in_user checks if a user id is stored in the session 
# and gets that user’s data from the database
@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            'SELECT * FROM user WHERE id = ?', (user_id,)
        ).fetchone()


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            flash("Insufficient permissions.")
            return redirect(url_for('auth.login'))

        return view(**kwargs)
    return wrapped_view

def admin_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            flash("Insufficient permissions.")
            return redirect(url_for('auth.login'))
        else:
            if g.user['role'] != 'admin':
                flash("Insufficient permissions.")
                return redirect(url_for('home'))

        return view(**kwargs)
    return wrapped_view


# @bp.route associates the URL /register with the register view
# function. When Flask receives a request to /auth/register, 
# it will call the register view and use the return value 
# as the response.
@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        firstname = request.form['firstname']
        lastname = request.form['lastname']
        username = request.form['username']
        password = request.form['password']
        city = request.form['city']
        state = request.form['state']
        zip_code = request.form['zip']

        db = get_db()
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif not firstname:
            error = 'Firstname is required.'
        elif not lastname:
            error = 'Lastname is required.'
        elif not city:
            error = 'City is required.'
        elif not state:
            error = 'State is required.'
        elif not zip_code:
            error = 'Zip code is required.'
        

        # ? placeholders for any user input, and a tuple of values to 
        # replace the placeholders with.
        elif db.execute(
            'SELECT id FROM user WHERE username = ?', (username,)
        ).fetchone() is not None:
            error = 'User {} is already registered.'.format(username)
        # fetchone() returns one row from the query. If the query returned 
        # no results, it returns None. Later, fetchall() is used, which 
        # returns a list of all results.


        if error is None:
            db.execute(
                'INSERT INTO user (username, password, first_name, second_name, city, state, zip, role) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
                (username, sha256_crypt.encrypt(password), firstname, lastname, city, state, zip_code, 'user')
            )
            db.commit()
            return redirect(url_for('auth.login'))

        flash(error)

    return render_template('auth/register.html')


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None
        user = db.execute(
            'SELECT * FROM user WHERE username = ?', (username,)
        ).fetchone()

        if user is None:
            error = 'Incorrect username.'
        try:
            if not sha256_crypt.verify(password, user['password']):
                error = 'Incorrect password.'
        except:
            error = 'Incorrect password.'
        

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('home'))
            # session is a dict that stores data across requests. 
            # When validation succeeds, the user’s id is stored in a 
            # new session. The data is stored in a cookie that is sent 
            # to the browser, and the browser then sends it back with 
            # subsequent requests. Flask securely signs the data so that 
            # it can’t be tampered with.

        flash(error)

    return render_template('auth/login.html')


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('auth.login'))

app/templates/contact.html
{% extends "layout.html" %}
{% block title %}
Contact
{% endblock %}
{% block content %}
<div class="container-fluid">
    <p>Contact</p>
</div>
{% endblock %}

app/templates/home.html
{% extends "layout.html" %}
{% block title %}
Home
{% endblock %}
{% block content %}
<div class="container-fluid">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger">
        <div class="flash">{{ message }}</div>
    </div>
    {% endfor %}
    <p>Home page.</p>
</div>
{% endblock %}

app/templates/information.html
{% extends "layout.html" %}
{% block title %}
Information
{% endblock %}
{% block content %}
<div class="container-fluid">
    <p>Information about the project</p>
</div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
    <head>
    {% block head %}
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <style type="text/css">
    @font-face {
        font-family: "Vafle-Regular";
        src: url("{{url_for('static', filename='fonts/Vafle VUT Regular.otf') }}") format("opentype");
        }
    </style>
    <!-- jQuery CDN -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- jquery ui and stylesheet very important to include in this order (before bootstrap)-->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Font Awesome JS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">


    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrapcdn.css')}}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">

    <link rel="stylesheet" href="{{ url_for('static', filename='sourtable_style.css')}}">
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>

    {% endblock %}

    </head>

    <body>

    <div class="wrapper">
            <!-- Sidebar  -->
            <nav id="sidebar" class="">
                <div class="sidebar-header">
                    <h3>Menu</h3>
                </div>
                <hr>
    
                <ul class="list-unstyled components">

                    <li class="active">
                        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Annotation</a>
                        <ul class="collapse list-unstyled" id="homeSubmenu">
                            <li>
                                <a href="{{ url_for('rating.sortable1') }}" class="navbar-item">Between six</a>
                            </li>
                            <li>
                                <a href="{{ url_for('rating.sortable2') }}" class="navbar-item">Between two</a>
                            </li>
                            <li>
                                <a href="{{ url_for('rating.sortable4') }}" class="navbar-item">One</a>
                            </li>
                            <li>
                                <a href="{{ url_for('rating.sortable3') }}" class="navbar-item">All types</a>
                            </li>
                        </ul>
                    </li>
                    <!-- <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
                        <ul class="collapse list-unstyled" id="pageSubmenu">
                            <li>
                                <a href="#">Page 1</a>
                            </li>
                            <li>
                                <a href="#">Page 2</a>
                            </li>
                            <li>
                                <a href="#">Page 3</a>
                            </li>
                        </ul>
                    </li> -->
                    <li>
                        <a href="{{ url_for('home') }}" class="navbar-item">Home</a>
                    </li>
                    <li>
                        <a href="{{ url_for('information') }}" class="navbar-item">Information</a>
                    </li>
                    <li>
                        <a href="{{ url_for('contact') }}" class="navbar-item">Contact</a>
                    </li>
                    <hr>
                    {% if not g.user %}
                    <li>
                        <a href="{{ url_for('auth.login') }}" class="navbar-item">Login</a>
                    </li>
                    <li>
                        <a href="{{ url_for('auth.register') }}" class="navbar-item">Register</a>
                    </li>
                    {% endif %}
                    {% if g.user %}
                    <li >
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">Logout</a>
                    </li>
                    <hr>
                    {% if g.user['role'] == "admin" %}
                    <li >
                            <a href="{{ url_for('upload.upload') }}" class="navbar-item">Upload images</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    {% if g.user %}
                    <li >
                        <div>
                        Logged in as <b>{{ g.user['username'] }}</b>
                        </div>
                    </li>
                    {% endif %}
                    

                </ul>
            </nav>
    
            <!-- Page Content  -->
            <div class="container">
                
                <div class="container" style="position:relative; height:1000px; width:100%;">
                <nav class="navbar navbar-expand-lg">
                            <button type="button" id="sidebarCollapse" class="btn btn-outline-dark" >
                                    <svg class="svg-inline--fa fa-align-left fa-w-14" aria-hidden="true" data-prefix="fas" data-icon="align-left" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M288 44v40c0 8.837-7.163 16-16 16H16c-8.837 0-16-7.163-16-16V44c0-8.837 7.163-16 16-16h256c8.837 0 16 7.163 16 16zM0 172v40c0 8.837 7.163 16 16 16h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16zm16 312h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm256-200H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16h256c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16z"></path></svg><!-- <i class="fas fa-align-left"></i> -->
                                    <span>Menu</span>
                            </button>

                </nav>
                    {% block content %}
                    {% endblock %}
                </div>
                
                <div class="container">
                <footer class="footer" >
                        <div class="container">
                            <p>Copyright ©2018.</p>
                        </div>
                </footer>
                </div>
            </div>


        </div>
    </body>
</html>